# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       mpris-scrobbler-signon

# >> macros
# << macros

Summary:    MPRIS Scrobbler Signon
Version:    0.1
Release:    1
Group:      Qt/Qt
License:    MIT
URL:        http://github.com/mariusor/mpris-scrobbler
Source0:    %{name}-%{version}.tar.bz2
Source100:  mpris-scrobbler-signon.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   jolla-settings-accounts >= 0.2.27
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)

%description
Signon helper for the mpris-scrobbler service.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
mkdir -p %{buildroot}%{_datadir}/accounts
mkdir -p %{buildroot}%{_datadir}/accounts/providers
mkdir -p %{buildroot}%{_datadir}/accounts/ui
mkdir -p %{buildroot}%{_datadir}/icons/hicolor/86x86/apps
mkdir -p %{buildroot}%{_datadir}/icons/hicolor/108x108/apps
mkdir -p %{buildroot}%{_datadir}/icons/hicolor/128x128/apps
mkdir -p %{buildroot}%{_datadir}/icons/hicolor/172x172/apps
mkdir -p %{buildroot}%{_datadir}/icons/hicolor/scalable/apps
#mkdir -p %{buildroot}%{_datadir}/accounts/services

install -m 644 icons/86x86/*.png %{buildroot}%{_datadir}/icons/hicolor/86x86/apps
install -m 644 icons/108x108/*.png %{buildroot}%{_datadir}/icons/hicolor/108x108/apps
install -m 644 icons/128x128/*.png %{buildroot}%{_datadir}/icons/hicolor/128x128/apps
install -m 644 icons/172x172/*.png %{buildroot}%{_datadir}/icons/hicolor/172x172/apps
install -m 644 icons/scalable/*.svg %{buildroot}%{_datadir}/icons/hicolor/scalable/apps
install -m 644 providers/*.provider %{buildroot}%{_datadir}/accounts/providers
install -m 644 ui/*.qml %{buildroot}%{_datadir}/accounts/ui
#install -m 644 services/*.service %{buildroot}%{_datadir}/accounts/services
# << install post

%files
%defattr(-,root,root,-)
%{_datadir}/accounts/ui/*.qml
%{_datadir}/accounts/providers/scrobbler-lastfm.provider
%{_datadir}/accounts/providers/scrobbler-librefm.provider
%{_datadir}/accounts/providers/scrobbler-listenbrainz.provider
%{_datadir}/icons/hicolor/86x86/apps/lastfm.png
%{_datadir}/icons/hicolor/86x86/apps/librefm.png
%{_datadir}/icons/hicolor/86x86/apps/listenbrainz.png
%{_datadir}/icons/hicolor/108x108/apps/lastfm.png
%{_datadir}/icons/hicolor/108x108/apps/librefm.png
%{_datadir}/icons/hicolor/108x108/apps/listenbrainz.png
%{_datadir}/icons/hicolor/128x128/apps/lastfm.png
%{_datadir}/icons/hicolor/128x128/apps/librefm.png
%{_datadir}/icons/hicolor/128x128/apps/listenbrainz.png
%{_datadir}/icons/hicolor/172x172/apps/lastfm.png
%{_datadir}/icons/hicolor/172x172/apps/librefm.png
%{_datadir}/icons/hicolor/172x172/apps/listenbrainz.png
%{_datadir}/icons/hicolor/scalable/apps/lastfm.svg
%{_datadir}/icons/hicolor/scalable/apps/librefm.svg
%{_datadir}/icons/hicolor/scalable/apps/listenbrainz.svg
%{_datadir}/icons/hicolor/scalable/apps/musicbrainz.svg
# >> files
# << files
